apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: manager-nfs-storage
  annotations:
    "storageClass.kubernetes.io/is-default-class": "true"
provisioner: nfs-storage
parameters:
  archiveOnDelete: "true"
reclaimPolicy: Retain
